apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-monkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaos-monkey
  template:
    metadata:
      labels:
        app: chaos-monkey
    spec:
      serviceAccountName: chaos-monkey
      containers:
      - name: chaos-monkey
        image: milisucevic/chaos-monkey:3.0.0
        command: ["python", "/app/chaos-monkey.py"]
