apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-workload
  namespace: workloads
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dummy-workload
  template:
    metadata:
      labels:
        app: dummy-workload
    spec:
      containers:
      - name: dummy-workload
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-workload
  namespace: workloads
spec:
  selector:
    app: dummy-workload
  ports:
  - name: http
    port: 80
    targetPort: 80